### ISSUE TITLE
Support word search from command line

### ISSUE THREAD

**Issue by zequnyu** [zequnyu/e2c#10]
For example, in Terminal, `e2c play` should return search result from the database. [click](https://click.palletsprojects.com/en/7.x/)

**Comment by edxu96** [comment]
The user can add some option to narrow down the searching scope. For example `$ e2c edward --name` will return results of `edward` searched within all English names.

**Comment by zequnyu** [comment]
@edxu96 This should be a separate issue/PR. We also don't have the classification info in the database so this will need extra work.

**Comment by zequnyu** [comment]
Closed by #15 and #20.
