### ISSUE TITLE
Terminal printing color support

### ISSUE THREAD

**Issue by zequnyu** [zequnyu/e2c#11]
[colorama](https://github.com/tartley/colorama)

**Comment by edxu96** [comment]
How about `search` returns a markdown snippet and print it using [terminal_markdown_viewer](https://github.com/axiros/terminal_markdown_viewer) (which is not maintained anymore) or [glow](https://github.com/charmbracelet/glow) (written in go) ? That way, to print multiple `search` results on paper, we can simply combine these markdown snippets.

Also, we can specify multiple ways to combine markdown snippets like comparing different words.

**Comment by zequnyu** [comment]
`search` should not return a markdown snippet. The return value is read by machine, not human. It makes no sense to wrap markdown rules at this point.

However, I'm not against adding features such as exporting markdown snippets or comparing words, but this issue should be contained to simply add colors to the output in Terminal.

Also, please avoid introducing packages from other languages unless it is really necessary, as we are trying to keep our package installation simple.

**Comment by zequnyu** [comment]
Closed by #23.
