### ISSUE TITLE
Highlight unfamiliar words in PDF files according to user' searching history

### ISSUE THREAD

**Issue by edxu96** [zequnyu/e2c#30]
- [How to Mark Text](https://pymupdf.readthedocs.io/en/latest/faq.html#how-to-mark-text)
- [Any way to highlight pdf document for given words via Python?](https://stackoverflow.com/questions/18690126/any-way-to-highlight-pdf-document-for-given-words-via-python?noredirect=1&lq=1)

**Comment by edxu96** [comment]
## Highlight multiple lines with one annotation

- [https://github.com/pymupdf/PyMuPDF/issues/285#issuecomment-520376629](https://github.com/pymupdf/PyMuPDF/issues/285)

**Comment by zequnyu** [comment]
I'm going to close this, per my [comment](https://github.com/zequnyu/e2c/issues/29#issuecomment-657286335).
