### ISSUE TITLE
Extract text from PDF files

### ISSUE THREAD

**Issue by edxu96** [zequnyu/e2c#31]
- [pdfminer/pdfminer.six](https://github.com/pdfminer/pdfminer.six): extract all text from PDF documents
- [PyMuPDF 1.17.3](https://github.com/pymupdf/PyMuPDF)
    * [Is it possible to extract highlighted text? #318](https://github.com/pymupdf/PyMuPDF/issues/318): an effective solution given by the author.
    * [How to extract text from a rectangle](https://github.com/pymupdf/PyMuPDF/wiki/How-to-extract-text-from-a-rectangle)
- [GitHub/0xabu/pdfannots](https://github.com/0xabu/pdfannots): very effective. But I don't know if it is legal to integrate the Python file in the project.

Will use `PyMuPDF` because it is actively maintained and easy to install.

_Originally posted by @edxu96 in https://github.com/zequnyu/e2c/issues/12#issuecomment-657010681_

**Comment by edxu96** [comment]
Text segmentation may be needed. For example, [fixing words with spaces using a dictionary look up in python?](https://stackoverflow.com/a/19675198/10181743)

**Comment by edxu96** [comment]
The current problem is how to fix broken words, "grid struc- ture" for example, caused by wrapping in the original file.

**Comment by zequnyu** [comment]
Seems to me the key line is `re.findall(r"\w+- \w+", s)`. My question is when we see `struc- ture` (pattern `xxx- xxx`), can we assume it is a word? I don't think you need to check if a word is in dictionary.

In short, you only need to check the pattern `re.findall(r"\w+- \w+", s)` and replace "- " with "" (empty). I think it is good enough at least for your PR to bring the functionality up.

**Comment by zequnyu** [comment]
On second thought, what happens when `xxx- xxx` is not a word? I think simply combining it makes sense. We might have some rare cases uncovered, but don't need to worry too much about them for now.

**Comment by edxu96** [comment]
If we use `re.findall(r"\w+- \w+", s)` only, there will be some wired word like `treeand` out of `tree- and cycle-based networks`. There are some dedicated word spell checking tools able to solve this problem.

I already implemented the second method with `nltk`. We need `nltk` in `TextBolb` (#13) anyway.

As for the `nltk.download('words')` part, we can do that in #34 .

**Comment by edxu96** [comment]
I found a better way using `TextBolb`.

```Python
from textblob import Word

for m in brokens:
        new = m.replace("- ", "")
        w = Word(new)
        if w.spellcheck()[0][1] >= 0.99:
            recovered = recovered.replace(m, new)
```

Still, some corpus is essential, which can be download in #34.
