### ISSUE TITLE
Separate features and database of the package

### ISSUE THREAD

**Issue by zequnyu** [zequnyu/e2c#34]
To meet pypi's file limit, we'll need to separate the database from the downloadable `.whl`.

Instead, we should provide:

`e2c download`

before using the package. Initialization check is needed as well.

**Comment by zequnyu** [comment]
Consider using:
[tqdm](https://github.com/tqdm/tqdm) for progress bar.
[requests](https://github.com/psf/requests) to download file.

**Comment by edxu96** [comment]
## Requests

- [Download large file in python with requests](https://stackoverflow.com/a/39217788/10181743)

**Comment by edxu96** [comment]
Do we need a `setup.py` in `/src/`?

**Comment by zequnyu** [comment]
Normally, `setup.py` should be in the root of the project path. In our case, we don't use.

**Comment by edxu96** [comment]
## Download `ntlk` corpora for `TextBolb`

https://github.com/zequnyu/e2c/pull/35#issuecomment-660285673

**Comment by zequnyu** [comment]
Closed by #38.
